apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ero3kb5by-python
  janus-idp.io/tekton: ero3kb5by-python
  backstage.io/kubernetes-id: ero3kb5by-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ero3kb5by-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
